cibotech/evilplot

- build.sbt
This disables publishing on the "root" aggregation project.
> Disable publish on root project.

- docs/src/main/tut/index.md
Point the api docs link at the evilplot package index instead of the root.
> Fix github link and update api docs link.

- shared/src/main/scala/com/cibo/evilplot/geometry/Drawable.scala
As it is, Polygons and paths report extents that represent the distance between the maximum and minimum X and Y points within their shape. That's a good guess of what an extent is: unfortunately, the renderer believes that everything is drawn between 0,0 and said extents. This means that a polygon that is far away from zero and is near the edge of the plot will never be rendered: For instance, try to render this:
```
Polygon(Seq(Point(0,0), Point(0,100),Point(100,0))).behind(
Style(Polygon(Seq(Point(30,0), Point(30,100),Point(50,100), Point(50,0))),RGB(200,180,20)).behind(
Style(Polygon(Seq(Point(72,2), Point(75,98), Point(186,200), Point(506,2))), RGB(0,200,200)).behind(
Style(Polygon(Seq(Point(62,7), Point(62,48), Point(86,48), Point(86,7))), RGB(0,255,0))
)
)
)
.write(new …
```
> fix extents in Polygons and Paths

- shared/src/main/scala/com/cibo/evilplot/plot/components/BorderPlot.scala
These changes fix two bugs:
1. Markers that exceed the size of the border plot push the border plot around.
2. The leftPlot had the wrong xtransform, causing the x-axis coordinates to be shrunk by a large factor.
The fixed plot looks like this:
> Fix to markers pushing border plots around

- build.sbt
This tries to fix an annoyance for intellij users. It should not be noticeable for pretty much anyone else.
IntelliJ Idea names its sbt projects with the same name as the Project() on the root dir, or the variable name that represents it. Therefore, without this change, it's named Root. This is quite the annoyance when looking at previously open projects, as one has to remember that root means evilplot. This gets even worse if one works on other scalajs projects that follow the same pattern.
Everything else should be unaffected, as all we are doing is changing the name of a build variable
> rename root project to help intellij

- CHANGELOG.md
- shared/src/main/scala/com/cibo/evilplot/demo/DemoPlots.scala
- shared/src/main/scala/com/cibo/evilplot/plot/BarChart.scala
- shared/src/main/scala/com/cibo/evilplot/plot/Histogram.scala
- shared/src/main/scala/com/cibo/evilplot/plot/renderers/BarRenderer.scala
This adds `BarRenderer.named`, which allows specifying a name and color to the legend context, especially in histograms.
> Add a named BarRenderer

- .travis.yml
- CHANGELOG.md
- project/Settings.scala
- shared/src/main/scala/com/cibo/evilplot/geometry/Drawable.scala
Re-enable the Scala 2.11 build. Adding the "-Xsource-2.12" compiler flag allows the custom apply methods on `Path` and `Polygon` to exist: https://github.com/scala/scala/releases/tag/v2.11.11
closes https://github.com/cibotech/evilplot/issues/23
> Re-enable build for Scala 2.11

- shared/src/main/scala/com/cibo/evilplot/colors/GradientUtils.scala
Makes `com.cibo.evilplot.colors.GradientUtils`, and its two helper methods for creating color gradients, public.
> Make GradientUtils public

- shared/src/main/scala/com/cibo/evilplot/plot/BoxPlot.scala
When a `Seq[Double]` passed to a boxplot has no variance, boxplot will render a line at the median of the data instead of rendering nothing.
Example:
```
val data = Seq(
Seq[Double](-1,2), 
Seq[Double](1,1,1), 
Seq[Double](3,4))
BoxPlot(data)
.standard()
.render(
```
> box plot displays a line when variance is zero

- shared/src/main/scala/com/cibo/evilplot/colors/GradientUtils.scala
- shared/src/main/scala/com/cibo/evilplot/demo/DemoPlots.scala
- shared/src/test/scala/com/cibo/evilplot/colors/ColoringSpec.scala
Multistop gradients were broken because the functionality was relying on `singleGradient`s being `PartialFunction[Double, Color]`s that were not defined outside of their range, then doing an `orElse` down the chain to pick the right one, but `singleGradient` had changed to be defined beyond the endpoints.
This has been changed by making the `multiGradient` function be defined beyond the endpoints, rather than the `singleGradient` partial function, plus adding a `singleGradientComplete` that is actually defined beyond the endpoints. This isn't a breaking change since `singleGradient` hasn't been a public method in any released version of EvilPlot.
> Fix multistop gradients

- .travis.yml
- shared/src/main/scala/com/cibo/evilplot/colors/GradientUtils.scala
Remove incorrect links in Scaladoc and add doc generation task to the Travis build to ensure that the documentation on master builds.
> Fix ScalaDoc generation

- CHANGELOG.md
- shared/src/main/scala/com/cibo/evilplot/plot/Plot.scala
- shared/src/test/scala/com/cibo/evilplot/plot/PlotSpec.scala
This allows conveniently just setting the lower bounds of a plot while retaining the current upper bounds. e.g.
plot.ybounds(lower = 0) keeps the current y upper bound but sets the y lower bound to 0.
> Add default args for Plot#xbounds and Plot#ybounds

- shared/src/main/scala/com/cibo/evilplot/demo/DemoPlots.scala
- shared/src/main/scala/com/cibo/evilplot/plot/components/Axes.scala
Quick support for basic discrete axis tick alignment. Discrete axes still make assumptions about the size of bands, but this should cover the use cases we've seen so far: mainly, labeling non-banded data with a discrete axis.
align 0:
align 0.5:
align 1:
> Add support for discrete axis tick alignment.

- shared/src/main/scala/com/cibo/evilplot/demo/DemoPlots.scala
- shared/src/main/scala/com/cibo/evilplot/plot/Heatmap.scala
Adds `apply` method to heatmap for use with continuous colorings
> add coloring apply to heatmap

- shared/src/main/scala/com/cibo/evilplot/plot/components/Axes.scala
Always uses the "in-bounds" labelling when bounds are fixed already, and uses the "expandable-bounds" version otherwise.
> Remove fixedBounds axes option.

- CHANGELOG.md
- shared/src/main/scala/com/cibo/evilplot/demo/DemoPlots.scala
- shared/src/main/scala/com/cibo/evilplot/plot/renderers/BoxRenderer.scala
Makes it possible to add a dashed line at the distribution's mean on any box plot, e.g.:
> Add withMeanLine method to BoxRenderer

- shared/src/main/scala/com/cibo/evilplot/colors/Color.scala
- shared/src/test/scala/com/cibo/evilplot/colors/ColorsSpec.scala
Evilplot has a gradient functionality useful outside of plots, which works just fine in situations where the output of.repr is sufficient to represent a color. Unfortunately, there are cases where it isn't, like building bitmaps.
I face two possibilities: One is to forget about Evilplot's coloring library across the board, and build another (with blackjack...), which would probably take too much time if done right, but would target replacing this part of Evilplot's infra. The other is just to expose the rgba conversion, which evilplot already has. 
This PR would do the second alternative. Note that, since Hues are represented as ints, and rounded immediately, roundtrip conversions get pretty lossy. Given that, in practice, browsers output to rgb, and only a small percentage of valid RGB …
> extract rgba values from colors

- shared/src/main/scala/com/cibo/evilplot/plot/components/PlotLine.scala
- shared/src/test/scala/com/cibo/evilplot/plot/components/FunctionPlotLineSpec.scala
Previous logic was using BigDecimal to guarantee inclusion of bounds. This method prepends and appends the bounds and "fills" the missing points in between.
> Switch to plain Double, guarantee bounds are included

- shared/src/main/scala/com/cibo/evilplot/colors/ColorBar.scala
- shared/src/test/scala/com/cibo/evilplot/colors/ColorsSpec.scala
Fix ScaledColorBar.colorIndex's handling of input data and add appropriate test conditions
This addresses an IndexOutOfBoundsException when inputs lower than the colorbar's minimum value are assigned an index. Inputs that are higher than the colorbar's maximum value were handled correctly.
Existing unit tests were updated to test these conditions.
> Fix colorbar failing when data is out of range

- shared/src/main/scala/com/cibo/evilplot/colors/GradientUtils.scala
Tiny addition to handle NaN in gradients (as fully transparent). There are likely other places where this could be handled in evilplot, too. I'll fix them as I run across them.
> Gracefully handle NaN in gradient functions

- shared/src/main/scala/com/cibo/evilplot/geometry/package.scala
This seems like a tiny little change, but on my system on a particular real-world test case, improves rendering performance by 75% (4 minutes --> 1 minute).
This `foldLeft` folds over a `Seq` which is subsequently appended to potentially _many_ times. Appending to the default collection `List` is unfortunately incredibly slow (its actually N-time where N is the length of the `List`! See: https://docs.scala-lang.org/overviews/collections/performance-characteristics.html), and Lists should not be used in performance-critical code which does appends. Now we know that this is actually performance critical in some situations!
> * change Seq to Vector

- build.sbt
- math/js/src/main/scala/com/cibo/evilplot/numeric/MatrixOperations.scala
- math/js/src/test/scala/com/cibo/evilplot/numeric/MatrixOperationsSpec.scala
- math/jvm/src/main/scala/com/cibo/evilplot/numeric/MatrixOperations.scala
- math/jvm/src/test/scala/com/cibo/evilplot/numeric/MatrixOperationsSpec.scala
- math/shared/src/main/scala/com/cibo/evilplot/numeric/MatrixOperationsI.scala
- project/Settings.scala
- shared/src/main/scala/com/cibo/evilplot/numeric/KernelDensityEstimation.scala
- shared/src/test/scala/com/cibo/evilplot/numeric/KernelDensityEstimationSpec.scala
This PR adds a new cross-built sub-module "evilplotMath" that provides 2 versions of the KernelDensityEstimation's old `matrixMatrixTransposeMult` function. 
The JS version is the old @zacharygraziano pure-Scala implementation (which can be to-js-transpiled), and the JVM version is now backed by Breeze matrix ops (after a goodly amount of array-copying 😢). This change also includes the `breeze-natives` JAR in the JVM dependencies which will use native extensions for that matrix-matrix multiply.
For contour plots, which may occur frequently in for instance, pairs-plots, on my system this decreases render time by 50%.
I moved and replicated the original tests for this method into both the JVM and JS directories (I think that will test the respective implementations?). All top-level tests …
> Provide native matrix-matrix multiply for ContourPlots

- .gitignore
- .travis.yml
- build.sbt
- js/src/main/scala/com/cibo/evilplot/DemoScatterInteraction.scala
- jupyter-scala/src/main/scala/com/cibo/evilplot/JupyterScala.scala
- jvm/src/main/scala/com/cibo/evilplot/geometry/Graphics2DSupport.scala
- project/Settings.scala
- project/build.properties
- project/plugins.sbt
- shared/src/main/scala/com/cibo/evilplot/colors/ColorUtils.scala
- shared/src/main/scala/com/cibo/evilplot/demo/DemoPlots.scala
- shared/src/test/scala/com/cibo/evilplot/colors/ColoringSpec.scala
I've added a cross-build for Scala 2.13 and upgraded evilplot's dependencies. Everything compiles and tests pass. I'd like to hand the code over to the maintainers to decide what to do with it. Note that jupyter-scala is no longer supported, so I migrated evilplot to use [almond.sh](https://almond.sh/) instead. This is for issue #95
> Added cross-build for Scala 2.13

- README.md
- version.sbt
The greatest published version is 0.8.0. I guess when that was published there was some misconfiguration that prevented the version getting bumped. 
Also, a bit confusing, I published a version 0.7.1 with some older dependencies about a week ago. That seems to show up as the "latest" version on the Download badge. So I added a link to Bintray where people can view all the versions.
> Set version.sbt to 0.8.1-SNAPSHOT

- .github/workflows/scala.yml
- project/Settings.scala
Redoing #146 because CI did weird things.
It looks like for a while now, the scalactic dependency has been erroneously marked as needed for runtime, rather than just for tests. This causes the scalactic version specified here to leak to any code that depends on evilplot. Since scalatest is marked as test-only in the dependencies here, this can cause scalatest and scalactic versions to go out of sync in downstream code, causing confusing compile errors. It seems like this issue has gone unnoticed because up until evilplot 0.9.0, we were using a fairly old version of scalatest; when we updated scalatest to 3.2.15, now suddenly we're overriding downstream code with a newer version of scalactic.
(For CIBO folks, https://github.com/cibotech/salus-one/pull/1197#discussion_r1389566666 for some …
> Make sure scalactic dependency doesn't leak to downstream projects 

- CHANGELOG.md
- version.sbt
This is a small patch release to prevent the scalactic dependency from leaking to downstream code.
Since no new features were added, there's no need to update the GH pages documentation site.
> Release 0.9.1
